<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Brady Heinig, Hunter Sanders, Eli Laddle, Dallin Draper">

<title>Final Project</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="stat_330_final_project_files/libs/clipboard/clipboard.min.js"></script>
<script src="stat_330_final_project_files/libs/quarto-html/quarto.js"></script>
<script src="stat_330_final_project_files/libs/quarto-html/popper.min.js"></script>
<script src="stat_330_final_project_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="stat_330_final_project_files/libs/quarto-html/anchor.min.js"></script>
<link href="stat_330_final_project_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="stat_330_final_project_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="stat_330_final_project_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="stat_330_final_project_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="stat_330_final_project_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Final Project</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Brady Heinig, Hunter Sanders, Eli Laddle, Dallin Draper </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<style type="text/css">
h1.title {
font-size: 40px;
text-align: center;
}
h4.author {
font-size: 40px;
text-align: center;
}
</style>
<div style="page-break-after: always;"></div>
<section id="abstract" class="level2">
<h2 class="anchored" data-anchor-id="abstract">Abstract</h2>
<p>This report uses Division 1 college basketball statistics from 2009-2021 to predict an NBA rookie’s season performance in terms of Wins Above Replacement (WAR) using multiple linear regression. Although we found that steals per game and box plus-minus were significant predictors, the overall predictive power of our model remained low. Moreover, our model failed to fully meet the assumptions of normality, impacting its reliability. Additionally, our analysis revealed that playing in a major NCAA conference did not significantly predict a rookie’s WAR statistic. These findings show how difficult it is to predict a rookie’s success using statistical models alone.</p>
</section>
<section id="problem-and-motivation" class="level1">
<h1>1 Problem and Motivation</h1>
<p>As a scout or general manager in the NBA, your job security is determined by how well you sniff out the prospects who end up being successful in the league. Drafting well is an art that few organizations have mastered, and there is no magic method that teams use to evaluate the potential of college and international prospects. With our project, we aim to assist these front offices in their drafting efforts by identifying key statistics and characteristics that can explain how valuable a player will be to their team during their rookie season. The metric we chose to harness in order to evaluate the player’s first season is WAR (Wins Above Replacement), because it takes into account both offensive and defensive metrics to provide a holistic view of a player’s overall performance while scaling based on minutes played.</p>
<section id="data-description" class="level2">
<h2 class="anchored" data-anchor-id="data-description">1.1 Data Description</h2>
<p>Data</p>
<p>This analysis uses data found on Kaggle called <a href="https://www.kaggle.com/datasets/adityak2003/college-basketball-players-20092021">College Basketball 2009-2021 + NBA Advanced Stats</a>, which was scraped and cleaned by Aditya Kumar. This dataset includes statistics for every division 1 college basketball player from 2009-2021, as well as WAR values for all NBA players from the same time period. It also includes statistics for the 2022 college basketball season, but it does not include those player’s NBA WAR values. Because of this, we will use this dataset to test our model after the model is trained and possible transformations are made.</p>
<p>The variables that were deemed relevant to this analysis are listed below:</p>
<p><em>war_total</em>: Total wins above replacement for that player for their entire rookie season. <em>mp</em>: Minutes played by that player per game during the final college season <em>treb</em>: Average total rebounds collected by the player per game during their final college season <em>stl</em>: Average total steals made by the player per game during their final college season <em>ast</em>: Average total assists made by the player per game during their final college season <em>usg</em>: Season average Usage percentage of player during their final college season <em>bpm</em>: Average box plus-minus per game during player’s final college season <em>drtg</em>: Season average defensive rating for each player <em>conf</em>: 1 if player played in a high major conference, 0 if they did not</p>
</section>
<section id="questions-of-interest" class="level2">
<h2 class="anchored" data-anchor-id="questions-of-interest">1.2 Questions of Interest</h2>
<p>The questions that we will look to answer in this project stem from the intended use of this data to evaluate possible NBA prospects. First, we want to discover the collegiate statistics that are most predictive of an NBA rookie’s total Wins Above Replacement (WAR). Secondly, we will investigate if a player’s participation in a major conference while in college determines their success during their NBA rookie season.</p>
</section>
<section id="regression-methods" class="level2">
<h2 class="anchored" data-anchor-id="regression-methods">1.3 Regression Methods</h2>
<p>The first question will be answered by fitting a linear regression model to our data and determining which statistics give us the highest predictive power. To answer the second question, we will fit a linear model and run tests of significance to determine if including a player’s NCAA conference affiliation helps explain their projected wins above replacement in their NBA rookie season.</p>
</section>
</section>
<section id="analyses-results-and-interpretation" class="level1">
<h1>2 Analyses, Results, and Interpretation</h1>
<section id="question-1" class="level2">
<h2 class="anchored" data-anchor-id="question-1">Question 1</h2>
<p>We have several variables in our dataset that could be used to predict rookie season WAR, so we used several variable selection methods to decide which predictors to include in our model.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = war_total ~ stl + bpm + GP + pts + treb + drtg + 
    conf, data = nba)

Residuals:
    Min      1Q  Median      3Q     Max 
-7.0760 -0.4715 -0.1135  0.3013  6.8979 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  5.248713   1.194803   4.393 1.34e-05 ***
stl          0.495596   0.106412   4.657 4.01e-06 ***
bpm          0.079398   0.022043   3.602 0.000344 ***
GP          -0.015509   0.009692  -1.600 0.110105    
pts         -0.038678   0.014155  -2.732 0.006487 ** 
treb         0.057516   0.026091   2.204 0.027903 *  
drtg         0.021736   0.011515   1.888 0.059597 .  
conf1       -0.178678   0.124965  -1.430 0.153329    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.194 on 557 degrees of freedom
Multiple R-squared:  0.09118,   Adjusted R-squared:  0.07976 
F-statistic: 7.983 on 7 and 557 DF,  p-value: 2.964e-09</code></pre>
</div>
</div>
<p>We chose to use the step wise selection method with AIC to give us our variables, because the model selected yielded the highest R^2 and adjusted R^2. This is our chosen model:</p>
<p><span class="math inline">\(\hat{war total}_i\)</span> <span class="math inline">\(=\)</span> <span class="math inline">\(5.248713\)</span> <span class="math inline">\(+\)</span> <span class="math inline">\(0.495596\)</span> <span class="math inline">\(\times\)</span> <span class="math inline">\(\text{stl}_i\)</span> <span class="math inline">\(+\)</span> <span class="math inline">\(0.079398\)</span> <span class="math inline">\(\times\)</span> <span class="math inline">\(\text{bpm}_i\)</span> <span class="math inline">\(-\)</span> <span class="math inline">\(0.015509\)</span> <span class="math inline">\(\times\)</span> <span class="math inline">\(\text{GP}_i\)</span> <span class="math inline">\(-\)</span> <span class="math inline">\(0.038678\)</span> <span class="math inline">\(\times\)</span> <span class="math inline">\(\text{pts}_i\)</span> <span class="math inline">\(+\)</span> <span class="math inline">\(0.057516\)</span> <span class="math inline">\(\times\)</span> <span class="math inline">\(\text{treb}_i\)</span> <span class="math inline">\(+\)</span> <span class="math inline">\(0.021736\)</span> <span class="math inline">\(\times\)</span> <span class="math inline">\(\text{drtg}_i\)</span> <span class="math inline">\(-\)</span> $0.178678 $ <span class="math inline">\(\times\)</span> <span class="math inline">\(\text{(conf = 1)}_i\)</span></p>
<p>Once the variables were selected, we then wanted to check to make sure there was no multicollinearity between the chosen predictors.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="stat_330_final_project_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>There was no indication that any of the variables were highly correlated, so that assumption was checked. We checked all other assumptions in the appendix, and all were sufficiently met except for normality of the residuals. Here is the output when checking our model for normality of residuals:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="stat_330_final_project_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="stat_330_final_project_files/figure-html/unnamed-chunk-4-2.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  hoops_lm$residuals
W = 0.83797, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Because this assumption was not met, we attempted to transform the response variable of our model. We used the Box-Cox test to discover the optimal lambda value to apply to our response variable, but the result was close enough to 1 so we chose not to apply any type of transformation.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="stat_330_final_project_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9494949</code></pre>
</div>
</div>
<p>Because the adjusted R^2 of 0.079 is so low, and the assumption of normality is not met, we cannot sufficiently say that a player’s rookie season WAR in the NBA can be predicted based on their last year of college stats. This makes sense due to the nature of scouting a prospect and how rookies assimilate to an NBA roster. Player evaluation includes detailed film study, interviews, and body measurables, all of which were not included in this dataset. We planned to test our model on a dataset of college basketball player stats from 2022, but due to the lack of explainability of our model, we decided it was best to not do so.</p>
</section>
<section id="question-2" class="level2">
<h2 class="anchored" data-anchor-id="question-2">Question 2</h2>
<p>Most of the highest rated high school and international players choose to play college basketball at a school found in one of the high major conferences (Big 12, Big 10, Pac-12, SEC, ACC, Big East). We wanted to see if a player’s rookie success in the NBA can be determined by their participation in one of these conferences. In our data, if a player played their final season in a major conference, their ‘conf’ value is 1, and 0 if they played in a mid major conference.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="stat_330_final_project_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The mean WAR is similar between players who played in high major conferences vs players who did not, but high major conference players have a wider range of rookie season WAR’s, likely due to the higher number of such players in our data. Because of the overlap of box plots, there does not appear to be a significant difference between to the two levels of conference.</p>
<p>To confirm this, we will create a model with ‘conf’ as the only predictor variable and test it’s significance.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = war_total ~ conf, data = nba)

Residuals:
    Min      1Q  Median      3Q     Max 
-7.5180 -0.4166 -0.1625  0.2071  7.4908 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  7.54519    0.09817  76.857   &lt;2e-16 ***
conf1       -0.01715    0.11610  -0.148    0.883    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.246 on 563 degrees of freedom
Multiple R-squared:  3.874e-05, Adjusted R-squared:  -0.001737 
F-statistic: 0.02181 on 1 and 563 DF,  p-value: 0.8826</code></pre>
</div>
</div>
<p>The p-value for the conf = 1 variable is well above 0.05, and therefore we conclude that by itself, the conference a player plays in is not a good predictor of rookie season WAR.</p>
</section>
</section>
<section id="conclusions" class="level1">
<h1>3 Conclusions</h1>
<p>Due to the limitations in our data previously mentioned, unfortunately we were unable to find a conclusion that is fully reliable. However, our analysis offers valuable insights for evaluating the potential impact of college players on NBA teams, particularly in predicting their Wins Above Replacement (WAR) scores during their rookie seasons.</p>
<p>From our analysis and testing, we found that out of the various predictor models we started out with, the ones that were most significant were steals, box plus-minus, games played, points, total rebounds, defensive rating, and conference status. We found these variables to be important through a stepwise sequential variable section method starting with our base model and using the AIC as our measurement. With these selected predictor variables, we were able to fit a linear model with WAR score as our response variable. With this model, we were able to find the coefficients for each predictor variable, thus being able to identify their individual impact while holding other variables constant.</p>
<p>With this data, we first and foremost learned that trying to predict a rookie’s impact on his NBA team through WAR score based on their final collegiate season statistics is rather difficult to do with much confidence. That being said, we have learned that there is a good chance that the previously mentioned variables are ones that are deserving of attention of scouts or anyone interested in a player’s NBA potential. We have also learned it does not appear that having played in one of the “High Major” conferences in college will boost a player’s WAR score for their first year in the NBA.</p>
</section>
<section id="contributions" class="level1">
<h1>4 Contributions</h1>
<p>Eli contributed by creating the framework of our project. He worked hard going through previous coding exercises from the class and gathering notes, descriptions, and examples of code for all the stages our project would have. This was extremely useful as we were then able to make quick progress once our data was properly set up. He also contributed by taking turns being the one to type as our group discussed what we needed to do for each stage of the project.</p>
<p>Brady contributed to the project by finding our data sets and joining them for us to be able to use. This was vital so that we could look at both stats from each player’s final college year as well as their NBA rookie year WAR score. He also worked hard to prepare this final report. Within the format, he was the one to gather the appropriate code needed for the Analysis section and provided the descriptions/interpretations for the various parts within it.</p>
<p>Dallin played an important part in our group project by being the one noting down all that we were doing in our analysis. This enabled us to have a detailed description of what we had done so that we could then organize all of our work properly and know what we had done to get the results we did. Dallin also aided in the organization of this final report by taking the format provided us and organizing the notes he took accordingly. He also was the one to completely put together the Abstract section of this report.</p>
<p>Hunter contributed to the overall project by being involved in the data cleaning and preparation stages. He analyzed the different data sets we had and determined which variables needed to be removed or adjusted in order to perform the analysis we wanted to do and created code to do so, such as the creation of dummy variables. He also took turns being the one to type and code as the group all discussed various stages of the project. As for this final report, he provided the Conclusion and Contributions sections.</p>
<p>Overall, our group worked together very well on this project. We all met together various times to work on it and this allowed us to collaborate with everyone on everything we did. There wasn’t anything done or decided in the process of our project without the whole group being a part of it.</p>
<section id="appendix" class="level2">
<h2 class="anchored" data-anchor-id="appendix">APPENDIX</h2>
<section id="data-cleaning" class="level3">
<h3 class="anchored" data-anchor-id="data-cleaning">Data Cleaning</h3>
</section>
<section id="multicollinearity" class="level3">
<h3 class="anchored" data-anchor-id="multicollinearity">Multicollinearity</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>first_half <span class="ot">&lt;-</span> <span class="fu">subset</span>(nba, <span class="at">select =</span> <span class="fu">c</span>(GP, pts, usg, Ortg, drtg, TS_per, FT_per, </span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>                                     TP_per, twoP_per, war_total, bpm))</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>second_half <span class="ot">&lt;-</span> <span class="fu">subset</span>(nba, <span class="at">select =</span> <span class="sc">-</span><span class="fu">c</span>(GP,</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>                                       </span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>                                       conf, Ortg, drtg, TS_per, FT_per, </span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>                                       TP_per, twoP_per, upperclassman))</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(first_half)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="stat_330_final_project_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(second_half)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="stat_330_final_project_files/figure-html/unnamed-chunk-9-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot</span>(<span class="fu">cor</span>(first_half), <span class="at">type =</span> <span class="st">"upper"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="stat_330_final_project_files/figure-html/unnamed-chunk-9-3.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot</span>(<span class="fu">cor</span>(second_half), <span class="at">type =</span> <span class="st">"upper"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="stat_330_final_project_files/figure-html/unnamed-chunk-9-4.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="question-1-1" class="level3">
<h3 class="anchored" data-anchor-id="question-1-1">Question 1</h3>
</section>
<section id="variable-selection" class="level3">
<h3 class="anchored" data-anchor-id="variable-selection">Variable Selection</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Split Predictors and Response</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>nba_x <span class="ot">&lt;-</span> <span class="fu">data.matrix</span>(nba[, <span class="dv">1</span><span class="sc">:</span><span class="dv">13</span>]) <span class="co"># predictors</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>nba_y <span class="ot">&lt;-</span> nba<span class="sc">$</span>war_total <span class="co"># response</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="co">#Elastic Net</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>elastic_net <span class="ot">&lt;-</span> <span class="fu">cv.glmnet</span>(<span class="at">x =</span> nba_x, <span class="co"># automatically includes a column of ones for the intercept FYI</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>                           <span class="at">y =</span> nba_y, </span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>                           <span class="at">type.measure =</span> <span class="st">"mse"</span>, </span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>                           <span class="at">alpha =</span> .<span class="dv">5</span>)  <span class="co"># .5 - this fits the elastic net with half ridge penalty, half LASSO penalty </span></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(elastic_net, <span class="at">se =</span> <span class="st">"lambda.1se"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>14 x 1 sparse Matrix of class "dgCMatrix"
                  s1
(Intercept) 7.532932
conf        .       
GP          .       
mp          .       
Ortg        .       
usg         .       
eFG         .       
TS_per      .       
FT_per      .       
TP_per      .       
twoP_per    .       
drtg        .       
bpm         .       
treb        .       </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Lasso Regression</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>lasso_reg <span class="ot">&lt;-</span> <span class="fu">cv.glmnet</span>(<span class="at">x =</span> nba_x, <span class="co"># automatically includes a column of ones for the intercept FYI</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>                           <span class="at">y =</span> nba_y, </span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>                           <span class="at">type.measure =</span> <span class="st">"mse"</span>, </span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>                           <span class="at">alpha =</span> <span class="dv">1</span>)  <span class="co"># .5 - this fits the elastic net with half ridge penalty, half LASSO penalty </span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(lasso_reg, <span class="at">se =</span> <span class="st">"lambda.1se"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>14 x 1 sparse Matrix of class "dgCMatrix"
                  s1
(Intercept) 7.532932
conf        .       
GP          .       
mp          .       
Ortg        .       
usg         .       
eFG         .       
TS_per      .       
FT_per      .       
TP_per      .       
twoP_per    .       
drtg        .       
bpm         .       
treb        .       </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Define base and full models</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>base_mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(war_total <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> nba) <span class="co"># Intercept only model </span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>full_mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(war_total <span class="sc">~</span> ., <span class="at">data =</span> nba) <span class="co"># All predictors in model </span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="co">#Backward with AIC </span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>backward_AIC <span class="ot">&lt;-</span> <span class="fu">step</span>(full_mod, <span class="co"># starting model for algorithm</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>                 <span class="at">direction =</span> <span class="st">"backward"</span>,</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>                 <span class="at">scope=</span><span class="fu">list</span>(<span class="at">lower=</span> base_mod, <span class="at">upper=</span> full_mod),</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>                 <span class="at">trace =</span> <span class="dv">0</span>)</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(backward_AIC)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = war_total ~ mp + usg + bpm + treb + ast + stl, data = nba)

Residuals:
    Min      1Q  Median      3Q     Max 
-7.1242 -0.4857 -0.1244  0.3244  6.9270 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  7.48892    0.34421  21.757  &lt; 2e-16 ***
mp          -0.02793    0.01201  -2.326  0.02037 *  
usg         -2.07825    1.36531  -1.522  0.12853    
bpm          0.03123    0.01574   1.984  0.04772 *  
treb         0.07621    0.02648   2.878  0.00416 ** 
ast          0.08626    0.04472   1.929  0.05424 .  
stl          0.49229    0.12241   4.022 6.58e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.196 on 558 degrees of freedom
Multiple R-squared:  0.08712,   Adjusted R-squared:  0.0773 
F-statistic: 8.875 on 6 and 558 DF,  p-value: 2.906e-09</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Stepwise with AIC</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>step_base_AIC <span class="ot">&lt;-</span> <span class="fu">step</span>(base_mod, <span class="co"># starting model for algorithm</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">direction =</span> <span class="st">"both"</span>,</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">scope=</span><span class="fu">list</span>(<span class="at">lower=</span> base_mod, <span class="at">upper=</span> full_mod),</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">trace =</span> <span class="dv">0</span>)</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(step_base_AIC)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = war_total ~ stl + bpm + GP + pts + treb + drtg + 
    conf, data = nba)

Residuals:
    Min      1Q  Median      3Q     Max 
-7.0760 -0.4715 -0.1135  0.3013  6.8979 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  5.248713   1.194803   4.393 1.34e-05 ***
stl          0.495596   0.106412   4.657 4.01e-06 ***
bpm          0.079398   0.022043   3.602 0.000344 ***
GP          -0.015509   0.009692  -1.600 0.110105    
pts         -0.038678   0.014155  -2.732 0.006487 ** 
treb         0.057516   0.026091   2.204 0.027903 *  
drtg         0.021736   0.011515   1.888 0.059597 .  
conf1       -0.178678   0.124965  -1.430 0.153329    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.194 on 557 degrees of freedom
Multiple R-squared:  0.09118,   Adjusted R-squared:  0.07976 
F-statistic: 7.983 on 7 and 557 DF,  p-value: 2.964e-09</code></pre>
</div>
</div>
</section>
<section id="new-linear-model-based-off-stepwise-aic" class="level3">
<h3 class="anchored" data-anchor-id="new-linear-model-based-off-stepwise-aic">New linear model based off stepwise, AIC</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>hoops_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(war_total <span class="sc">~</span> stl <span class="sc">+</span> bpm <span class="sc">+</span> GP <span class="sc">+</span> pts <span class="sc">+</span> treb <span class="sc">+</span> drtg <span class="sc">+</span> </span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>    conf, <span class="at">data =</span> nba)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(hoops_lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = war_total ~ stl + bpm + GP + pts + treb + drtg + 
    conf, data = nba)

Residuals:
    Min      1Q  Median      3Q     Max 
-7.0760 -0.4715 -0.1135  0.3013  6.8979 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  5.248713   1.194803   4.393 1.34e-05 ***
stl          0.495596   0.106412   4.657 4.01e-06 ***
bpm          0.079398   0.022043   3.602 0.000344 ***
GP          -0.015509   0.009692  -1.600 0.110105    
pts         -0.038678   0.014155  -2.732 0.006487 ** 
treb         0.057516   0.026091   2.204 0.027903 *  
drtg         0.021736   0.011515   1.888 0.059597 .  
conf1       -0.178678   0.124965  -1.430 0.153329    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.194 on 557 degrees of freedom
Multiple R-squared:  0.09118,   Adjusted R-squared:  0.07976 
F-statistic: 7.983 on 7 and 557 DF,  p-value: 2.964e-09</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Add residuals</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>nba<span class="sc">$</span>residuals <span class="ot">&lt;-</span> hoops_lm<span class="sc">$</span>residuals</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="assumptions" class="level3">
<h3 class="anchored" data-anchor-id="assumptions">Assumptions</h3>
<div class="cell">
<div class="cell-output-display">
<p><img src="stat_330_final_project_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 4 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 3 rows containing missing values or values outside the scale range
(`geom_text()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="stat_330_final_project_files/figure-html/unnamed-chunk-15-2.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  hoops_lm$residuals
W = 0.83797, p-value &lt; 2.2e-16</code></pre>
</div>
<div class="cell-output-display">
<p><img src="stat_330_final_project_files/figure-html/unnamed-chunk-15-3.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="stat_330_final_project_files/figure-html/unnamed-chunk-15-4.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 7 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1 row containing missing values or values outside the scale range
(`geom_text()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="stat_330_final_project_files/figure-html/unnamed-chunk-15-5.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 7 rows containing missing values or values outside the scale range
(`geom_point()`).
Removed 1 row containing missing values or values outside the scale range
(`geom_text()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="stat_330_final_project_files/figure-html/unnamed-chunk-15-6.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="vif" class="level3">
<h3 class="anchored" data-anchor-id="vif">VIF</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>vifs <span class="ot">&lt;-</span> <span class="fu">vif</span>(hoops_lm)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(vifs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.631187</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(vifs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.703283</code></pre>
</div>
</div>
</section>
<section id="log-transformations" class="level3">
<h3 class="anchored" data-anchor-id="log-transformations">Log Transformations</h3>
<div class="cell">
<div class="cell-output-display">
<p><img src="stat_330_final_project_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9494949</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log(war_total) ~ mp + usg + bpm + treb + stl + ast, 
    data = nba)

Residuals:
    Min      1Q  Median      3Q     Max 
-6.4687 -0.0592  0.0072  0.0744  0.6317 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  2.065847   0.092137  22.421  &lt; 2e-16 ***
mp          -0.002786   0.003214  -0.867  0.38646    
usg         -0.958873   0.365465  -2.624  0.00894 ** 
bpm          0.003000   0.004214   0.712  0.47684    
treb         0.018073   0.007089   2.549  0.01106 *  
stl          0.084218   0.032767   2.570  0.01042 *  
ast          0.011013   0.011970   0.920  0.35792    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.32 on 558 degrees of freedom
Multiple R-squared:  0.03914,   Adjusted R-squared:  0.02881 
F-statistic: 3.788 on 6 and 558 DF,  p-value: 0.001042</code></pre>
</div>
</div>
</section>
<section id="rechecking-assumptions" class="level3">
<h3 class="anchored" data-anchor-id="rechecking-assumptions">RECHECKING ASSUMPTIONS</h3>
<div class="cell">
<div class="cell-output-display">
<p><img src="stat_330_final_project_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1 row containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1 row containing missing values or values outside the scale range
(`geom_text()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="stat_330_final_project_files/figure-html/unnamed-chunk-18-2.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  transform_lm$residuals
W = 0.33051, p-value &lt; 2.2e-16</code></pre>
</div>
<div class="cell-output-display">
<p><img src="stat_330_final_project_files/figure-html/unnamed-chunk-18-3.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="stat_330_final_project_files/figure-html/unnamed-chunk-18-4.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 3 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing missing values or values outside the scale range
(`geom_text()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="stat_330_final_project_files/figure-html/unnamed-chunk-18-5.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>